# Generated by Django 4.0.4 on 2022-05-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title_tag',
            field=models.CharField(default='Timeless Blog', max_length=100),
        ),
    ]
