# Generated by Django 4.0.4 on 2022-05-29 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publication_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='title_tag',
            field=models.CharField(max_length=100),
        ),
    ]
