# Generated by Django 4.0.4 on 2022-06-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_article_snippets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='snippets',
        ),
    ]
